### ISSUE TITLE
Move In seneca-mvp code

### ISSUE THREAD

**Issue by mcdonnelldean** [Concorda/concorda-dashboard#1]
This will form the basis of our first demo.
- Do a full copy of seneca-mvp
- Remove any non 'user management' specific stuff
- Add a transport pin to listen for 'role:user,cmd:*' to manage external messages.

**Comment by mihaidma** [comment]
I told @mirceaalexandru about the status and what needs to get modified in Vidi to make it work.

The integration is finished on branch `plugin`.
Partially working MVPs are made (one simulating the client and the other simulating the concorda admin) are pushed to the `boilerplate` branch.

**Comment by mcdonnelldean** [comment]
@mihaidma Awesome stuff man! Good work
