### ISSUE TITLE
Need user list component

### ISSUE THREAD

**Issue by mcdonnelldean** [Concorda/concorda-dashboard#11]
We need to be able to list all users in concorda. We'll use #10 to edit them.

**Comment by mcdonnelldean** [comment]
@mirceaalexandru From the UI I am going to call something like, `/api/users` I expect it to give me the users list grouped by app. The lists I get should vary depending on my current logged in user in concorda (not all concorda users should be able to see all apps being managed)

**Comment by mirceaalexandru** [comment]
@geek I think we should something like:

 /api/user/group/:groupId

This will return users registered for a specified service.

/api/user will return users, each with list of groups.

Also we will need for these services support for:
- limit - to limit number of items returned
- skip - to skip a number of items
- order - control order of users.

This is required as we will need pagination for user list. I will opena another issue for pagination support.

**Comment by mcdonnelldean** [comment]
@mirceaalexandru This looks solid. Only change is /api/user/group should return the list of groups with their users. I think /api/user should return a list of all the users in a single list (access permitting).

Agreed on the limit / skip / order. We won't need these for the demo this week so let's add that issue to next week's iteration. We can add some nice UI then to take advantage of them.

**Comment by mcdonnelldean** [comment]
Closed by merge
