### ISSUE TITLE
Implement support for request reset password in UI

### ISSUE THREAD

**Issue by mirceaalexandru** [Concorda/concorda-dashboard#117]
Add reset password in login screen which will open a page. 

In the request reset password page there will be a text (email) field and submit button. Submit should call  

```
POST /auth/create_reset
```

with request body a JSON:

```
email: 'user email'
```

Another page that can be accessed on url:

```
#/resetPassword/{token}
```

will contain two password fields for resetting password and a submit button.

Action:

```
POST
/auth/execute_reset
```

body contains:
token,
password
repeat.

For this service details can be found here:
https://github.com/senecajs/seneca-auth

**Comment by mcdonnelldean** [comment]
@ckiss @mirceaalexandru Do you have enough UI to do this screen or do you need some work UI help on this one?

**Comment by ckiss** [comment]
@mcdonnelldean I'll do the screen with what I have and if you think it needs more work, it can be done after that. is that ok with you?

**Comment by ckiss** [comment]
ref #128

**Comment by ckiss** [comment]
done by #128
