### ISSUE TITLE
Create email template

### ISSUE THREAD

**Issue by mirceaalexandru** [Concorda/concorda-dashboard#119]
I will need a html template for emails sent from Concorda. It should use same colors as Concorda's UI.

I need for reset password email, invite to register email and in the future for notifications email.
It should allow me to display the email text inside.

@mcdonnelldean @thefoxis

**Comment by mcdonnelldean** [comment]
@thefoxis I think these are just html / css all-in-ones. Pop them into /server/templates as html files.

**Comment by thefoxis** [comment]
indeed, it's just HTML (table layout) and inline CSS. no webfonts though. will do!

**Comment by mcdonnelldean** [comment]
Nice! Awesome stuff :+1:

**Comment by mirceaalexandru** [comment]
For reset password I will have a text like this:

```
Hello, 

Somebody requested a reset password for this account: 
mircea.alexandru@gmail.com 
If you did not request that, just ignore this email.
If you want to reset your password please click on the link bellow:
Reset Password


All the best,
Concorda team
```

**Comment by mirceaalexandru** [comment]
@thefoxis Add there the template, I will then create the template for each type of E-mail I am sending.

Just mark with a HTML comment the place where I can insert my text in the template.

**Comment by thefoxis** [comment]
@mirceaalexandru — the template can be found [here](https://github.com/nearform/concorda/tree/master/server/templates). I used the reset password copy, it should be pretty straightforward to use / modify content. let me know if you have any questions.

you might want to do some adjustments depending on how you're sending the emails (campaign monitor, mailchimp, madrill, etc.).

**Comment by mirceaalexandru** [comment]
@thefoxis thank you, I will update them with what I need.
