### ISSUE TITLE
npm test portability

### ISSUE THREAD

**Issue by feugy** [Concorda/concorda-dashboard#184]
When using npm test on windows, it fails due to lack of glob expression support.
You can use lab's pattern to get the equivalent:

```
  "scripts": {
    "test": "lab test --pattern \.test -r console -v -L -m 3000",
```

lab automatically adds the `.js` suffix, and consider the parameter as a regular expression on the file name.

**Comment by mirceaalexandru** [comment]
changed to use env variables, script removed.
