### ISSUE TITLE
Move to ES7

### ISSUE THREAD

**Issue by mcdonnelldean** [Concorda/concorda-dashboard#19]
Same as https://github.com/nearform/vidi-dashboard/issues/54

**Comment by salmanm** [comment]
Did that in https://github.com/nearform/bluebeard/commit/92770be31a828616fdeed566831f9145df78495e. happy to add it in this repo. should I?

**Comment by mcdonnelldean** [comment]
@salmanm That would be epic we need it for both repos :D

**Comment by ckiss** [comment]
hi @salmanm. I assigned this to you. Please let me know if you don't have time for this and I'll do it myself :) Thanks

**Comment by salmanm** [comment]
Apologies, no, I'll do it today. :100:

**Comment by salmanm** [comment]
@mcdonnelldean @ckiss Fixed in https://github.com/nearform/concorda/pull/49
