### ISSUE TITLE
User Icon as Concorda logo

### ISSUE THREAD

**Issue by mcdonnelldean** [Concorda/concorda-dashboard#39]
We don't yet have a logo for Concorda. It is a user management system so I am thinking some sort of simple user Icon for now would be great. You are totally free to design the actual icon with all the glory that goes with it but for now a temporary user head will do perfect.

**Comment by thefoxis** [comment]
I did something very similar to Vidi, a circle with three user icons in it. We can revisit that later if you'd like to!
