### ISSUE TITLE
Use similar path parameter style for Hapi and Express

### ISSUE THREAD

**Issue by mirceaalexandru** [Concorda/concorda-dashboard#43]
Related with https://github.com/senecajs/seneca-web/issues/42

**Comment by mirceaalexandru** [comment]
waiting for latest seneca-web to be published to change url for update the project and close this

**Comment by mirceaalexandru** [comment]
Well, I need to do some small changes to Concorda to use the parameters like this

/api/user/:id

insted of 

/api/user/{id}

like it is now so I will re-open this.

**Comment by mcdonnelldean** [comment]
@mirceaalexandru Did that change get published in the end?

**Comment by mirceaalexandru** [comment]
Closed in Concorda repository
