### ISSUE TITLE
Make sure favicon gets served

### ISSUE THREAD

**Issue by thefoxis** [Concorda/concorda-dashboard#52]
I've added a favicon [here](https://github.com/nearform/concorda/blob/master/client/index.html#L9) but unsure about the asset pipeline. The path to image is `assets/img/favicon.png`, no errors are thrown but just want an additional pair of :eyes: to make sure this is correct to be serving this asset. Right now Chrome thinks it's `text/html`, not an image.

**Comment by mcdonnelldean** [comment]
Not actually sure how to fix this :D @salmanm @AdrianRossouw Maybe?

**Comment by salmanm** [comment]
@mcdonnelldean @thefoxis Looks like we're not copying the static assets into the `dist` directory. All other images/css are being loaded via webpack `loader`s, however this file is directly `link`ed into `index.html`.

I do it using [copyfiles](https://github.com/calvinmetcalf/copyfiles). I've pushed a potential fix for it [here](https://github.com/nearform/concorda/compare/serve-static) just for demonstrating it. It copies all files from `assets/static` into `dist/assets` which can then be referenced easily.

If you don't want a new route `/assets` and do not have any other static file (needed to be served without webpack) then copy only `favicon.png` into `dist/assets`

**Comment by mcdonnelldean** [comment]
@salmanm Cheers, I went slightly simpler, see, https://github.com/nearform/concorda/pull/76. Although I can't get chrome to actually request the favicon, or at least it is not showing up in my network options.

**Comment by thefoxis** [comment]
It does get pulled down but with wrong mime type of `text/html`.

**Comment by salmanm** [comment]
You might wanna add a slash before img path making it path relative to
root. Else our react routes get confused.

**Comment by thefoxis** [comment]
that's exactly what I've got right now: 

```
<link rel="icon" type="image/png" href="/dist/img/favicon.png">
```

unfortunately, it still results in:
![screen shot 2016-01-27 at 12 38 25](https://cloud.githubusercontent.com/assets/375731/12601143/e3bbd0a0-c4f2-11e5-8070-da370666a17e.png)

**Comment by salmanm** [comment]
Dist not required
