### ISSUE TITLE
Forms validation

### ISSUE THREAD

**Issue by ckiss** [Concorda/concorda-dashboard#62]

**Comment by ckiss** [comment]
@mcdonnelldean have you done any research on this? what should we use for forms validations?

**Comment by mcdonnelldean** [comment]
For now just enough to not allow complete garbage, do it in the component itself. We can look at something fancy down the road.

**Comment by salmanm** [comment]
https://github.com/erikras/redux-form is pretty useful but painfully slow. We can try it though, newer version could be faster. Let me know if I can jump in.

**Comment by ckiss** [comment]
@mcdonnelldean I would like to use something right from the beginning so we don't have to revisit this in the future. What do you think about @salmanm suggestion? I like this from it too: Initializing From State. @salmanm of course you can jump in :) have you used this in the past? The functionality it offers seems pretty tempting.

**Comment by ckiss** [comment]
@salmanm I looked at the client-side validation http://erikras.github.io/redux-form/#/examples/synchronous-validation?_k=arlsuk and wrt speed it looks good to me

**Comment by salmanm** [comment]
Yes I've used it and found it to be great. It automatically binds all the
handlers and keeps the state in sync. Gives a nice way to handle async
validations as well.

**Comment by ckiss** [comment]
nice, thanks. I think I'm going to use it. do you have anything against this @mcdonnelldean? :D

**Comment by salmanm** [comment]
Yes, may be, I used a couple of months ago, and it was slow, I even doubt
that it's not the redux-form that is slow, it could be the rapid state
change and keeping Redux DevTools open makes it slow

**Comment by ckiss** [comment]
cool, thanks @salmanm :D

**Comment by mcdonnelldean** [comment]
Lets bring it in and see how it looks, if it's slow I'll pull it out but if it works lets use it.
