### ISSUE TITLE
Move add button above the list

### ISSUE THREAD

**Issue by mcdonnelldean** [Concorda/concorda-dashboard#65]
We should probably have this in it's own toolbox above the list.

The feedback was once the list grew too long the button would be at the bottom.

**Comment by ckiss** [comment]
@mcdonnelldean isn't this more suited for @thefoxis? :D I'm not really good with this :)

**Comment by mcdonnelldean** [comment]
Oops, sorry assigned wrong. Yup, for @thefoxis
