### ISSUE TITLE
User not being immediately logged out on deleting themselves

### ISSUE THREAD

**Issue by CodeWriterWriter** [Concorda/concorda-dashboard#66]
The current build of Concorda is kicking you when you're logged in and delete the user you're currently logged in as, but only when you navigate to Overview, and then back to Users.
The user should be kicked once the delete themselves, to prevent them from deleting other users afterwards.

**Comment by mcdonnelldean** [comment]
@CodeWriterWriter Can you add the same issue to vidi. @mirceaalexandru Is working on the backend bits to set this up, we will then use a live socket to kill the browser. Not assigned as I will merge all session killing into one issue soon.

**Comment by mcdonnelldean** [comment]
@mirceaalexandru @ckiss Is this fixed?

**Comment by mirceaalexandru** [comment]
No, is not fixed.

I will take a look

**Comment by mirceaalexandru** [comment]
fixed, on next action the user will be redirected to logout page.
