### ISSUE TITLE
User cannot change their password

### ISSUE THREAD

**Issue by shanel262** [Concorda/concorda-dashboard#67]
When the user selects to edit an account, only the name and email can be changed and not the password.

**Comment by mcdonnelldean** [comment]
@ckiss @mirceaalexandru This should be allowed in Concorda (but not Vidi). @ckiss Assigned to you.

**Comment by mirceaalexandru** [comment]
To change a password the request should contain both password && repeat fields, with identical values.

If no password should be changed then these fields should be missing or empty in the request body for update user.

**Comment by mirceaalexandru** [comment]
@ckiss an old bug in seneca-user...

**Comment by mcdonnelldean** [comment]
@ckiss Is this done? There's a merge ref above

**Comment by ckiss** [comment]
@mcdonnelldean yup, but we found a bug in seneca-user which will be fixed today. I'll let Mircea close this after he fixes the issue

**Comment by mcdonnelldean** [comment]
Awesome stuff :dancer:

**Comment by mirceaalexandru** [comment]
fixed by 

https://github.com/senecajs/seneca-user/pull/33

I will close it after seneca-user's PR is merged.

**Comment by mirceaalexandru** [comment]
tested and working
