### ISSUE TITLE
Editing email to be the same as a pre-existing email changes the pre-existings Name

### ISSUE THREAD

**Issue by CodeWriterWriter** [Concorda/concorda-dashboard#68]
If you edited User1's email to be the same as User2's it allows it.
Also, it doesn't change the email of User1, but changes the name of User2 to match User1.
You then have 2 User1 with 2 different email address.

**Comment by mcdonnelldean** [comment]
@mirceaalexandru Ideas on how to prevent this? I don't think two users should ever have the same email address.

**Comment by mcdonnelldean** [comment]
@ckiss This mostly likely involves returning a validation error from the server so when @mirceaalexandru responds on how to handle can you look at this?

**Comment by mirceaalexandru** [comment]
I am already returning for each service something like 

{err: true | false, msg: 'some err message in case of error', data: {some data, in case no error} }

I will take a look on server side to see what is happening.

**Comment by mirceaalexandru** [comment]
@ckiss actually I will change that to match the structure from login/logout and other auth services with

ok: true | false, why: '....', data: .....

Is that OK?

**Comment by ckiss** [comment]
@mirceaalexandru sounds great. is this change in place already?

**Comment by mirceaalexandru** [comment]
@ckiss no, it will be today...soon

**Comment by ckiss** [comment]
awesome, thanks @mirceaalexandru

**Comment by mirceaalexandru** [comment]
@CodeWriterWriter can you please try to reproduce this issue.

When you try to update a user using a existing user email the following response is received:

{"ok":false,"why":"email-exists"}

Now I see here two problems:
- the message is not friendly enough to be displayed to the user.
- @ckiss can you please take a look and display the error message - if ok: false ?

**Comment by ckiss** [comment]
@mirceaalexandru we don't have an errors handling flow in place just yet, but if the server works properly don't worry about this. I'll address the issue when I have what I need to display errors.

**Comment by CodeWriterWriter** [comment]
@mirceaalexandru Attempting to change the email to someone elses email now doesn't change anyones email, or name. The normal changing email functionality is still working

**Comment by mirceaalexandru** [comment]
OK, then somebody can also please check this issue and if it not reproducible we can close it.

Please do a 

rm -rf node_modules && npm install && npm run build && npm run start 
to make sure latest seneca-user is used.

**Comment by mirceaalexandru** [comment]
@CodeWriterWriter yes, that is because the request is reporting error. You can see in Network tab the response for that update user request.
