### ISSUE TITLE
on delete user action the list of users should be reloaded from db, not filtered locally

### ISSUE THREAD

**Issue by mirceaalexandru** [Concorda/concorda-dashboard#69]

**Comment by mcdonnelldean** [comment]
@mirceaalexandru agreed. @ckiss You will need to swap the action buttons for a refresh icon while the operation is happening, otherwise the UI will look slow.

**Comment by mcdonnelldean** [comment]
@ckiss Leave the button swap out here. Just have some state that shows we are deleting. I'll talk to @thefoxis about how to handle update flow in the UI

**Comment by ckiss** [comment]
done
