### ISSUE TITLE
Iteration 001 - 2016.01.26

### ISSUE THREAD

**Issue by mirceaalexandru** [Concorda/concorda-dashboard#8]
Tasks for this iteration:
- #5 - Add login
- #6 - Integrate Vidi login
- #7 - Add register/update user

**Comment by mcdonnelldean** [comment]
@mirceaalexandru Going to close this and open new ones for you.

**Comment by mihaidma** [comment]
I started some public Trello board, in case not used I should delete it: https://trello.com/senecauser

**Comment by mcdonnelldean** [comment]
@mihaidma You can drop them for now, I'm going to make a merged one later today.
