### ISSUE TITLE
User navigation numbers overlap copyright text when users list is 10 users or more

### ISSUE THREAD

**Issue by CodeWriterWriter** [Concorda/concorda-dashboard#88]

**Comment by thefoxis** [comment]
Not longer happening. @CodeWriterWriter can you label and assign issues if you discover something in the front-end please? Wouldn't see it if I wasn't reading through the unfiltered list.

**Comment by mcdonnelldean** [comment]
@thefoxis I'll make you a new frontend label across the board. @CodeWriterWriter It's better to put a briefer description and the issue in the body, big titles make issues harder to read.
